language: objective-c
before_install:
  - brew install nvm
  - nvm install 0.12
install:
  - npm install
  - npm install -g gulp
  - npm install -g bower
  - npm install -g cordova
  - npm install -g ionic
  - bower install
before_script:
  - gulp tests
  - ionic state restore
script: ionic build ios