language: objective-c
xcode_sdk: iphoneos8.1
before_install:
  - curl "https://nodejs.org/dist/latest-v4.x/node-v4.2.2.pkg" > "$HOME/Downloads/node-latest.pkg" && sudo installer -store -pkg "$HOME/Downloads/node-latest.pkg" -target "/"
install:
  - npm install node-sass
  - npm install
  - npm install -g gulp
  - npm install -g bower
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g ios-deploy
  - bower install
before_script:
  - gulp tests
  - ionic state restore
script: ionic build ios
after_script:
  - find $HOME/build/gexplorer/babysizr/platforms/ios