language: objective-c
xcode_sdk: iphoneos8.1
before_install:
  - node --version
  - npm --version
  - curl "https://nodejs.org/dist/latest-v4.x/node-v4.2.2.pkg" > "$HOME/Downloads/node-latest.pkg" && sudo installer -store -pkg "$HOME/Downloads/node-latest.pkg" -target "/"
install:
  - node --version
  - npm --version
  - npm install
  - npm install -g gulp
  - npm install -g bower
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g ios-deploy
  - npm install -g ios-sim
  - bower install
before_script:
  - gulp tests
  - ionic state restore
script:
  - ionic build ios --target="iPhone-5"
after_script:
  - find $HOME/build/gexplorer/babysizr/platforms/ios
