language: objective-c
xcode_sdk: iphoneos8.1
cache:
  directories:
  - $HOME/.nvm
before_install:
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh
  - export NVM_DIR=~/.nvm
  - nvm install 4.2.2
install:
  - npm install
  - npm install -g gulp
  - npm install -g bower
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g ios-deploy
  - bower install
before_script:
  - gulp tests
  - ionic state restore
script: ionic build ios
after_script:
  - find $HOME/build/gexplorer/babysizr/platforms/ios