language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra
before_install:
  - nvm install 0.12
install:
  - npm install
  - npm install -g gulp
  - npm install -g bower
  - npm install -g cordova
  - npm install -g ionic
  - bower install
before_script:
  - gulp tests
  - ionic state restore
script: ionic build android